name: url_launcher_utils
description: "A reusable Flutter abstraction over url_launcher for calls, SMS, email, messaging apps, maps, and browser URLs."
version: 0.1.1
homepage: https://github.com/belabiedredouane
repository: https://github.com/belabiedredouane/url_launcher_utils
issue_tracker: https://github.com/belabiedredouane/url_launcher_utils/issues
topics:
  - url-launcher
  - mail
  - maps
  - whatsapp
  - utils

environment:
  sdk: ^3.6.0
  flutter: ">=3.27.0"

dependencies:
  flutter:
    sdk: flutter
  url_launcher: ^6.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
